import {Quote} from "../model/Quote.ts";

// the seed date put in local database
export const sampleQuotes: Quote[] = [
    {
        id: 1,
        text: "The only way to do great work is to love what you do.",
        author: "Steve Jobs",
        source: "Stanford Commencement Speech",
        isFavorite: true,
    },
    {
        id: 2,
        text: "In the middle of difficulty lies opportunity.",
        author: "Albert Einstein",
        source: "",
        isFavorite: false,
    },
    {
        id: 3,
        text: "Your time is limited, so don’t waste it living someone else’s life.",
        author: "Steve Jobs",
        source: "",
        isFavorite: true,
    },
    {
        id: 4,
        text: "Simplicity is the ultimate sophistication.",
        author: "Leonardo da Vinci",
        source: "",
        isFavorite: false,
    },
    {
        id: 5,
        text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        author: "Winston Churchill",
        source: "",
        isFavorite: true,
    },
    {
        id: 6,
        text: "The future belongs to those who believe in the beauty of their dreams.",
        author: "Eleanor Roosevelt",
        source: "",
        isFavorite: false,
    },
    {
        id: 7,
        text: "Be yourself; everyone else is already taken.",
        author: "Oscar Wilde",
        source: "",
        isFavorite: true,
    },
    {
        id: 8,
        text: "The best way to predict the future is to invent it.",
        author: "Alan Kay",
        source: "",
        isFavorite: false,
    },
    {
        id: 9,
        text: "Life is what happens when you're busy making other plans.",
        author: "John Lennon",
        source: "",
        isFavorite: true,
    },
    {
        id: 10,
        text: "The purpose of our lives is to be happy.",
        author: "Dalai Lama",
        source: "",
        isFavorite: false,
    },
    {
        id: 11,
        text: "Keep your face always toward the sunshine—and shadows will fall behind you.",
        author: "Walt Whitman",
        source: "",
        isFavorite: true,
    },
    {
        id: 12,
        text: "If you can dream it, you can do it.",
        author: "Walt Disney",
        source: "",
        isFavorite: false,
    },
    {
        id: 13,
        text: "It always seems impossible until it's done.",
        author: "Nelson Mandela",
        source: "",
        isFavorite: true,
    },
    {
        id: 14,
        text: "To live is the rarest thing in the world. Most people exist, that is all.",
        author: "Oscar Wilde",
        source: "",
        isFavorite: false,
    },
    {
        id: 15,
        text: "We become what we think about.",
        author: "Earl Nightingale",
        source: "",
        isFavorite: false,
    },
    {
        id: 16,
        text: "What you do speaks so loudly that I cannot hear what you say.",
        author: "Ralph Waldo Emerson",
        source: "",
        isFavorite: false,
    },
    {
        id: 17,
        text: "Happiness depends upon ourselves.",
        author: "Aristotle",
        source: "",
        isFavorite: true,
    },
    {
        id: 18,
        text: "Act as if what you do makes a difference. It does.",
        author: "William James",
        source: "",
        isFavorite: false,
    },
    {
        id: 19,
        text: "Everything has beauty, but not everyone sees it.",
        author: "Confucius",
        source: "",
        isFavorite: false,
    },
    {
        id: 20,
        text: "Do what you can, with what you have, where you are.",
        author: "Theodore Roosevelt",
        source: "",
        isFavorite: true,
    },
    {
        id: 21,
        text: "Turn your wounds into wisdom.",
        author: "Oprah Winfrey",
        source: "",
        isFavorite: false,
    },
    {
        id: 22,
        text: "The journey of a thousand miles begins with one step.",
        author: "Lao Tzu",
        source: "",
        isFavorite: true,
    },
    {
        id: 23,
        text: "Knowing yourself is the beginning of all wisdom.",
        author: "Aristotle",
        source: "",
        isFavorite: false,
    },
    {
        id: 24,
        text: "The mind is everything. What you think you become.",
        author: "Buddha",
        source: "",
        isFavorite: true,
    },
    {
        id: 25,
        text: "It does not matter how slowly you go as long as you do not stop.",
        author: "Confucius",
        source: "",
        isFavorite: false,
    },
    {
        id: 26,
        text: "Everything you can imagine is real.",
        author: "Pablo Picasso",
        source: "",
        isFavorite: false,
    },
    {
        id: 27,
        text: "You miss 100% of the shots you don’t take.",
        author: "Wayne Gretzky",
        source: "",
        isFavorite: true,
    },
    {
        id: 28,
        text: "Whatever you are, be a good one.",
        author: "Abraham Lincoln",
        source: "",
        isFavorite: false,
    },
    {
        id: 29,
        text: "Whether you think you can, or you think you can’t—you’re right.",
        author: "Henry Ford",
        source: "",
        isFavorite: true,
    },
    {
        id: 30,
        text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
        author: "Aristotle",
        source: "",
        isFavorite: false,
    },
];
